rails3-and-4/config/routes.rb
Rails3::Application.routes.draw do
  
  resources :books do
    collection do
      get :fiction
      get :history
      get :sports
    end
  end
  
  resources :dvds do
    collection do
      get :drama
      get :action
      get :comedy
    end
  end
  
  resources :musics do
    collection do
      get :rock
      get :pop
      get :alternative
    end
  end
  
  root :to => 'books#index'

  get 'gist' => 'gist#load', :as => :gist
  get 'examples' => 'examples#index', :as => :examples
    
  

end

rails3-and-4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def render_dummy
    render :text => "Content", :layout => true
  end
  
end

rails3-and-4/app/controllers/books_controller.rb
class BooksController < ApplicationController
    
  def index
    render_dummy
  end
  
  def fiction
    render_dummy
  end
  
  def history
    render_dummy
  end
  
  def sports
    render_dummy
  end
  
  
end

rails3-and-4/app/controllers/dvds_controller.rb
class DvdsController < ApplicationController

  def index
    render_dummy
  end

  def drama
    render_dummy
  end
  
  def action
    render_dummy
  end
  
  def comedy
    render_dummy
  end
  
end

rails3-and-4/app/controllers/gist_controller.rb
class GistController < ApplicationController

  def load
    render :partial => 'gist/load', :locals => {:gist => params[:gist]}, :layout => 'gist'
  end
  
end

rails3-and-4/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    render_dummy
  end
end

rails3-and-4/app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  
  def index
    render_dummy
  end
  
  def rock
    render_dummy
  end
  
  def pop
    render_dummy
  end
  
  def alternative
    render_dummy
  end

end

rails3-and-4/app/helpers/application_helper.rb
module ApplicationHelper

  def example(options={}, &block)
    out = render :partial => 'examples/header', :locals => {:options => options}
    out << capture(&block)
    out << (render :partial => 'examples/footer', :locals => {:options => options})
    out
  end

end

rails3-and-4/app/views/examples/_example_1.html.haml
.example
  = example :title => 'Example 1: Simple Nested Sidebar Navigation', :haml => '87147', :sass => '87435', :css => '87440' do
    #example_1.example_content.no_anchor
      #navigation= render_navigation
      .content
        .breadcrumbs
          .title breadcrumbs:
          = render_navigation(:renderer => :breadcrumbs, :join_with => ' &raquo; ')
      .clear_float

rails3-and-4/app/views/examples/_example_2.html.haml
.example
  = example :title => 'Example 2: Simple Main Navigation (Tabbed)', :haml => '87433', :sass => '87438', :css => '87443' do
    #example_2.example_content
      #top_navigation= render_navigation(:level => 1)
      .clear_float
      .content
        .breadcrumbs
          .title breadcrumbs:
          = render_navigation(:renderer => :breadcrumbs, :join_with => ' &raquo; ')

rails3-and-4/app/views/examples/_example_3.html.haml
.example
  = example :title => 'Example 3: Tabbed Main Navigation with Sidebar Sub Navigation', :haml => '87434', :sass => '87439', :css => '87445' do
    #example_3.example_content
      #top_navigation= render_navigation(:level => 1)
      .clear_float
      .content_wrapper
        #sub_navigation= render_navigation(:level => 2)
        .content
          .breadcrumbs
            .title breadcrumbs:
            = render_navigation(:renderer => :breadcrumbs, :join_with => ' &raquo; ')
        .clear_float    

rails3-and-4/app/views/examples/_example_4.html.haml
.example
  = example :title => 'Example 4: Javascript Menu with Superfish', :haml => '279476', :sass => '279472', :css => '279470' do
    #example_4.example_content
      #js_navigation= render_navigation(:expand_all => true)
      .content
        .breadcrumbs
          .title breadcrumbs:
          = render_navigation(:renderer => :breadcrumbs, :join_with => ' &raquo; ')
      .clear_float

:javascript
  $(document).ready(function(){ 
    $("#js_navigation ul").superfish(); 
  });

rails3-and-4/app/views/examples/_footer.html.haml
.footer
  .src_code
    Source Code:
    = link_to 'Haml', gist_path(:gist => options[:haml])
  .styling
    Style:
    = link_to 'Sass', gist_path(:gist => options[:sass])
    |
    = link_to 'Css', gist_path(:gist => options[:css])
  .clear_float

rails3-and-4/app/views/examples/_header.html.haml
.header= options[:title]

rails3-and-4/app/views/gist/_load.html.haml
%script{:src => "http://gist.github.com/#{gist}.js"}

rails3-and-4/app/views/layouts/_gist.html.haml
!!! Strict
%html
  %head
    %meta{'http-equiv' => 'Content-Type', :content => 'text/html; charset=UTF-8'}/
    %title simple-navigation Examples
    = stylesheet_link_tag 'navigation'
    = javascript_include_tag 'jquery', 'application'
  %body
    
    = render :partial => 'structure/header'
    
    #main_content
    
      = link_to 'Back to examples', root_path
      %div{:style => 'margin-bottom: 10px'}
      = yield
      

rails3-and-4/app/views/layouts/application.html.haml
!!! Strict
%html
  %head
    %meta{'http-equiv' => 'Content-Type', :content => 'text/html; charset=UTF-8'}/
    %title simple-navigation Examples
    = stylesheet_link_tag 'navigation', 'example_1', 'example_2', 'example_3', 'example_4'
    = javascript_include_tag 'jquery', 'application', 'jquery.superfish'
  %body
    
    = render :partial => 'structure/header'
    
    #main_content
    
      = render :partial => 'structure/info_box'
      
      = render :partial => 'examples/example_1'
      
      = render :partial => 'examples/example_2'
      
      = render :partial => 'examples/example_3'
        
      = render :partial => 'examples/example_4'
                        

rails3-and-4/app/views/structure/_header.html.haml
#top_header
  .title simple-navigation gem Examples
  .sub
    by
    = link_to 'codeplant', 'http://www.codeplant.ch'

rails3-and-4/app/views/structure/_info_box.html.haml
#info_box
  The styling of these examples has been tested with Firefox 3 and Safari 3/4.

  .section
    .title Source Code
    .info
      simple-navigation gem:
      = link_to 'http://github.com/codeplant/simple-navigation', 'http://github.com/codeplant/simple-navigation'
  .section
    .title Documentation
    .info
      simple-navigation gem Wiki:
      = link_to 'http://wiki.github.com/codeplant/simple-navigation', 'http://wiki.github.com/codeplant/simple-navigation'
  .section
    .title Discussion and Feedback
    .info
      Google Group: 
      = link_to 'http://groups.google.com/group/simple-navigation', 'http://groups.google.com/group/simple-navigation'
  .section
    .info
      All examples shown here are based on 
      = link_to 'this config/navigation.rb', gist_path(:gist => '87452')
      file.